version: 2
updates:
  # Maintain NuGet dependencies for main library
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "07:00"
    ignore:
      - dependency-name: "Kentico.Xperience.*"
    open-pull-requests-limit: 5

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "07:00"
    open-pull-requests-limit: 5
