//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace DancingGoat.Models
{
	/// <summary>
	/// Represents a content item of type <see cref="Reference"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Reference : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "DancingGoat.Reference";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// ReferenceName.
		/// </summary>
		public string ReferenceName { get; set; }


		/// <summary>
		/// ReferenceDescription.
		/// </summary>
		public string ReferenceDescription { get; set; }


		/// <summary>
		/// ReferenceText.
		/// </summary>
		public string ReferenceText { get; set; }


		/// <summary>
		/// ReferenceImage.
		/// </summary>
		public IEnumerable<Image> ReferenceImage { get; set; }
	}
}