//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DancingGoat.Models
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="IProductFields"/> reusable schema assigned.
	/// </summary>
	public interface IProductFields
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "ProductFields";


		/// <summary>
		/// ProductFieldsName.
		/// </summary>
		public string ProductFieldsName { get; set; }


		/// <summary>
		/// ProductFieldsDescription.
		/// </summary>
		public string ProductFieldsDescription { get; set; }


		/// <summary>
		/// ProductFieldsShortDescription.
		/// </summary>
		public string ProductFieldsShortDescription { get; set; }


		/// <summary>
		/// ProductFieldsImage.
		/// </summary>
		public IEnumerable<Image> ProductFieldsImage { get; set; }
	}
}