//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DancingGoat.Models
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="ISEOFields"/> reusable schema assigned.
	/// </summary>
	public interface ISEOFields
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "SEOFields";


		/// <summary>
		/// SEOFieldsTitle.
		/// </summary>
		public string SEOFieldsTitle { get; set; }


		/// <summary>
		/// SEOFieldsDescription.
		/// </summary>
		public string SEOFieldsDescription { get; set; }


		/// <summary>
		/// SEOFieldsAllowSearchIndexing.
		/// </summary>
		public bool SEOFieldsAllowSearchIndexing { get; set; }
	}
}