//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace DancingGoat.Models
{
	/// <summary>
	/// Represents a content item of type <see cref="Event"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Event : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "DancingGoat.Event";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// EventTitle.
		/// </summary>
		public string EventTitle { get; set; }


		/// <summary>
		/// EventHeroBannerImage.
		/// </summary>
		public IEnumerable<Image> EventHeroBannerImage { get; set; }


		/// <summary>
		/// EventPromoText.
		/// </summary>
		public string EventPromoText { get; set; }


		/// <summary>
		/// EventDate.
		/// </summary>
		public DateTime EventDate { get; set; }


		/// <summary>
		/// EventCafe.
		/// </summary>
		public IEnumerable<Cafe> EventCafe { get; set; }
	}
}